import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import GameIndicator from "@common/components/game-indicator";
import DialogContainer from "@common/components/dialog/dialog-container";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SimHUB',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
      <html lang="en">
        <body className={inter.className}>
            <main>
                <GameIndicator />
                {children}
            </main>
            <DialogContainer />
        </body>
      </html>
  )
}
