import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import GameIndicator from "./common/game-indicator/game-indicator";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SimHUB',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
      <html lang="en">
        <body className={inter.className}>
            <GameIndicator name="Assetto Corsa" />
            {children}
        </body>
      </html>
  )
}
